"""FaceFiltering: modular classical filters + registry."""

from facefiltering.registry import (
    CATEGORY_NAMES,
    CONVOLUTION_FILTERS,
    FILTER_FUNCTIONS,
    FILTER_METHODOLOGIES,
    FILTERS_BY_CATEGORY,
    FILTERS_BY_FUNCTION,
    FILTERS_BY_METHODOLOGY,
    FILTER_CATEGORIES,
    FILTER_NAMES,
    FILTERS_BY_TYPE,
    FILTER_TYPES,
    FUNCTION_NAMES,
    METHODOLOGY_DESCRIPTIONS,
    METHODOLOGY_NAMES,
    TYPE_DESCRIPTIONS,
    TYPE_NAMES,
    categories_for_type,
    filters_for_methodology_and_function,
    filters_for_type_and_category,
    functions_for_methodology,
    apply_filter,
)
from facefiltering.validate import FilterInputError, ensure_bgr_u8

__all__ = [
    "CATEGORY_NAMES",
    "CONVOLUTION_FILTERS",
    "FUNCTION_NAMES",
    "FILTERS_BY_CATEGORY",
    "FILTERS_BY_FUNCTION",
    "FILTER_CATEGORIES",
    "FILTER_FUNCTIONS",
    "METHODOLOGY_NAMES",
    "METHODOLOGY_DESCRIPTIONS",
    "FILTER_METHODOLOGIES",
    "FILTERS_BY_METHODOLOGY",
    "TYPE_NAMES",
    "TYPE_DESCRIPTIONS",
    "FILTER_TYPES",
    "FILTERS_BY_TYPE",
    "functions_for_methodology",
    "filters_for_methodology_and_function",
    "categories_for_type",
    "filters_for_type_and_category",
    "FILTER_NAMES",
    "apply_filter",
    "ensure_bgr_u8",
    "FilterInputError",
]
